// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoj23WQIUFGhp_LOTg1YwFmF748LtQPzk',
    appId: '1:231590330906:web:f34a4c8e449c51d10e87a3',
    messagingSenderId: '231590330906',
    projectId: 'horas-v3-ae2e9',
    authDomain: 'horas-v3-ae2e9.firebaseapp.com',
    storageBucket: 'horas-v3-ae2e9.firebasestorage.app',
    measurementId: 'G-8VB0JQC7PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZc0c_b8PsVPi1lhJmR63weGW_Hkzm01Q',
    appId: '1:231590330906:android:3ca65bf05e5a8ac20e87a3',
    messagingSenderId: '231590330906',
    projectId: 'horas-v3-ae2e9',
    storageBucket: 'horas-v3-ae2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGJD9SvG8qANwEjgDvFMJW3sObtLsJX4',
    appId: '1:231590330906:ios:d6de0e75ff16af090e87a3',
    messagingSenderId: '231590330906',
    projectId: 'horas-v3-ae2e9',
    storageBucket: 'horas-v3-ae2e9.firebasestorage.app',
    iosBundleId: 'com.example.testeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoj23WQIUFGhp_LOTg1YwFmF748LtQPzk',
    appId: '1:231590330906:web:801b2bb5711e62e20e87a3',
    messagingSenderId: '231590330906',
    projectId: 'horas-v3-ae2e9',
    authDomain: 'horas-v3-ae2e9.firebaseapp.com',
    storageBucket: 'horas-v3-ae2e9.firebasestorage.app',
    measurementId: 'G-7766PSMGY7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOQ9b6D3_XuLzHS8Ben-Td6Z6HnSK3uGI',
    appId: '1:225586733848:ios:57376f59b2afbd7b5e746d',
    messagingSenderId: '225586733848',
    projectId: 'teste-horas-v3',
    storageBucket: 'teste-horas-v3.firebasestorage.app',
    iosBundleId: 'com.example.testeFirebase',
  );

}